theme: jekyll-theme-hacker
title: STRONTIC
show_downloads: false
title-img: strontic-box-logo-white2-transparent.png
markdown: GFM
github:
  repository_url: null
  zip_url: null
  tar_url: null
  another_url: null
