#Theme configuration
theme: jekyll-theme-hacker
title: STRONTIC
show_downloads: false
github:
  repository_url: https://github.com/strontic
  zip_url: null
  tar_url: null
  another_url: null
url: https://strontic.github.io
plugins:
  - jekyll-sitemap
markdown: GFM
highlighter: rouge
destination: ./Docs

#Build: This prevents MD files from being duplicated into the destination directory (if different directory)
optional_front_matter:
  remove_originals: true
