theme: jekyll-theme-cayman
title: STRONTIC
avatar: strontic-favicon.png
title-img: strontic-box-logo-white2-transparent.png


### FOOTER ###

social-network-links:
  email: "info@strontic.com"
  facebook: strontic
  github: strontic
  twitter: strontic20
  instagram: strontic20
  reddit: strontic
  linkedin: company/strontic
  youtube: channel/UC4f4ncsTlo-2VlNlXz6x6Bg
  rss: true
#  xing: 
#  stackoverflow: 
#  snapchat: 
#  spotify: 
#  telephone:
#  steam: 
#  twitch: 
#  yelp: 
#  telegram: 
#  calendly: 
