#Theme configuration
remote-theme: strontic/hacker
title: STRONTIC
show_downloads: false
github:
  repository_url: https://github.com/strontic
  zip_url: null
  tar_url: null
  another_url: null
markdown: GFM
highlighter: rouge
